#Deployment
###controllers/pb-deploy.tml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruits-api 
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fruits-api 
  template:
    metadata:
      labels:
        app: fruits-api 
    spec:
      containers:
      - name: fruits-api 
        image: vrbabu/fruitsapi01:v0.1 
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1'
            memory: '1G'
          requests:
            cpu: '1'
            memory: '1G'
        ports:
        - containerPort: 80
